package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	"github.com/Jonathan-Zollinger/Gospel-TUI/graph/model"
)

// Verses is the resolver for the verses field.
func (r *queryResolver) Verses(ctx context.Context) ([]*model.Verses, error) {
	return r.verses, nil
}

// Chapters is the resolver for the chapters field.
func (r *queryResolver) Chapters(ctx context.Context) ([]*model.Chapters, error) {
	return r.chapters, nil
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context) ([]*model.Books, error) {
	return r.books, nil
}

// Volumes is the resolver for the volumes field.
func (r *queryResolver) Volumes(ctx context.Context) ([]*model.Volumes, error) {
	return r.volumes, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
