// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Books struct {
	ID             *int        `json:"id"`
	VolumeID       *int        `json:"volume_id"`
	BookTitle      string      `json:"book_title"`
	BookLongTitle  *string     `json:"book_long_title"`
	BookSubtitle   *string     `json:"book_subtitle"`
	BookShortTitle *string     `json:"book_short_title"`
	BookLdsURL     *string     `json:"book_lds_url"`
	Chapters       []*Chapters `json:"chapters"`
}

type Chapters struct {
	ID            *int      `json:"id"`
	BookID        *int      `json:"book_id"`
	ChapterNumber int       `json:"chapter_number"`
	Verses        []*Verses `json:"verses"`
}

type Verses struct {
	ID            *int   `json:"id"`
	ChapterID     int    `json:"chapter_id"`
	VerseNumber   int    `json:"verse_number"`
	ScriptureText string `json:"scripture_text"`
}

type Volumes struct {
	ID               *int     `json:"id"`
	VolumeTitle      string   `json:"volume_title"`
	VolumeLongTitle  *string  `json:"volume_long_title"`
	VolumeSubtitle   *string  `json:"volume_subtitle"`
	VolumeShortTitle *string  `json:"volume_short_title"`
	VolumeLdsURL     *string  `json:"volume_lds_url"`
	Books            []*Books `json:"books"`
}
